public class AvoidTooLongClassCheck
{
    public void method()
    {// Noncompliant {{A Class should not have more than 150 lines}}
        int a;
        int b;

        b = 6;
        a = 1;
        a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;
        a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;
        a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;
        a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;
        a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;
        a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;
        a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;
        a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;
        a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;
        a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;
        a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;
        a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;
        a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;
        a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;
        a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;
        a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;
        a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;
        a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;
        a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;
        a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;
        a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;
        a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;
        a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;
        a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;
        a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;
        a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;
        a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;
        a = b + 1;
        b = a - 1;
        a = 2;
        b = 2 * a + 1;
        a = b + 1;
        b = a - 1;
    }
}
